# Generated by Django 3.1 on 2022-06-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('Assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, help_text='The file of assignment', upload_to='assignments_files/')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the resource was created')),
                ('deadline_date', models.DateTimeField(help_text='The date and time the assignment is deadline.', null=True)),
                ('textbox', models.TextField(help_text='The comment of The assignment')),
                ('title', models.CharField(help_text="The title's assignment", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the Classes', max_length=255)),
                ('semester', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the classroom was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the Stream', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="The Student's first name or names.", max_length=50)),
                ('last_name', models.CharField(help_text="The Student's last name or names.", max_length=50)),
                ('email', models.EmailField(help_text='The contact email for the student.', max_length=254)),
                ('roll_no', models.CharField(max_length=50)),
                ('username', models.CharField(help_text="The Student's username.", max_length=255, unique=True)),
                ('password', models.CharField(help_text="The Student's password.", max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="The Teacher's first name or names.", max_length=50)),
                ('last_name', models.CharField(help_text="The Teacher's last name or names.", max_length=50)),
                ('email', models.EmailField(help_text='The contact email for the teacher.', max_length=254)),
                ('username', models.CharField(help_text="The Teacher's username.", max_length=255, unique=True)),
                ('password', models.CharField(help_text="The Teacher's password.", max_length=100)),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Submits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.SmallIntegerField(help_text='The comment of The resource')),
                ('status', models.SmallIntegerField(help_text='The status of submit has 2 value: 0: yet , 1: done')),
                ('file', models.FileField(blank=True, help_text='The file of submit', upload_to='Submits_files/')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="The title's resource", max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the resource was created')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="The title's resource", max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the resource was created')),
                ('textbox', models.TextField(help_text='The comment of The resource')),
                ('file', models.FileField(help_text='The file of resource', upload_to='')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.sections')),
            ],
        ),
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='stream_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.stream'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.sections'),
        ),
    ]
