# Generated by Django 3.1 on 2022-06-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Assignments',
        ),
    ]
