# Generated by Django 3.1 on 2022-06-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_authentication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Assignment_id',
            new_name='assignment_id',
        ),
    ]
