# Generated by Django 3.1 on 2022-06-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20220623_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
