# Generated by Django 3.1 on 2022-06-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20220623_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
