# Generated by Django 3.1 on 2022-06-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20220623_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
