# Generated by Django 3.1 on 2022-06-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20220623_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
